theme: jekyll-theme-minimal
title: [Unifysell]
description: [Zugriff auf Shop-APIs über eine Schnittstelle.]

author:
  name: 'unifysell team'
  github_username:  unifysell
  email: info@unifysell.de
